import type { Platter } from './types';

export const platters: Platter[] = [
  {
    id: 'simple-daily',
    name: 'Simple Daily Platter',
    description: 'Everyday balanced meal that is quick to prepare and nutritious.',
    emoji: '🍽️',
    bestFor: 4,
    difficulty: 'easy',
    estimatedTime: '45 min',
    dishes: {
      subji: 'Aloo Gobi',
      dal: 'Moong Dal',
      rice: 'Plain Rice',
      bread: 'Roti',
      sweet: 'Suji Halwa',
      drink: 'Buttermilk (Chaas)',
      side: 'Papad',
    },
  },
  {
    id: 'festival',
    name: 'Festival Platter',
    description: 'Rich and festive spread for celebrations and special occasions.',
    emoji: '🪔',
    bestFor: 6,
    difficulty: 'medium',
    estimatedTime: '90 min',
    dishes: {
      subji: 'Malai Kofta',
      dal: 'Dal Makhani',
      rice: 'Peas Pulao',
      bread: 'Naan-style Tawa Roti',
      sweet: 'Gulab Jamun (Ready Mix)',
      drink: 'Thandai',
      side: 'Raita',
    },
  },
  {
    id: 'student-program',
    name: 'Student Program Platter',
    description: 'Budget-friendly, filling, and easy to cook in a hostel or PG.',
    emoji: '📚',
    bestFor: 4,
    difficulty: 'easy',
    estimatedTime: '40 min',
    dishes: {
      subji: 'Aloo Matar',
      dal: 'Moong Dal',
      rice: 'Jeera Rice',
      bread: 'Roti',
      sweet: 'Coconut Ladoo',
      drink: 'Nimbu Pani (Lemonade)',
      side: 'Papad',
    },
  },
  {
    id: 'light-dinner',
    name: 'Light Dinner Platter',
    description: 'Easy on the stomach, perfect for a relaxed evening meal.',
    emoji: '🌙',
    bestFor: 4,
    difficulty: 'easy',
    estimatedTime: '35 min',
    dishes: {
      subji: 'Paneer Bhurji',
      dal: 'Moong Dal',
      rice: 'Curd Rice',
      bread: 'Roti',
      sweet: 'Rice Kheer',
      drink: 'Buttermilk (Chaas)',
      side: 'Mint Chutney',
    },
  },
  {
    id: 'protein-rich',
    name: 'Protein-Rich Platter',
    description: 'High-protein satvik meal for fitness and strength.',
    emoji: '💪',
    bestFor: 4,
    difficulty: 'easy',
    estimatedTime: '50 min',
    dishes: {
      subji: 'Palak Paneer',
      dal: 'Chana Dal',
      rice: 'Jeera Rice',
      bread: 'Plain Paratha',
      sweet: 'Gajar Halwa',
      drink: 'Mango Lassi',
      side: 'Raita',
    },
  },
  {
    id: 'ekadashi',
    name: 'Ekadashi Platter',
    description: 'Fasting-friendly meal with no grains, suitable for Ekadashi vrat.',
    emoji: '🙏',
    bestFor: 4,
    difficulty: 'easy',
    estimatedTime: '30 min',
    dishes: {
      subji: 'Aloo Gobi',
      dal: 'Moong Dal',
      rice: 'Plain Rice',
      bread: 'Puri',
      sweet: 'Coconut Ladoo',
      drink: 'Nimbu Pani (Lemonade)',
      side: 'Sabudana Khichdi',
    },
  },
  {
    id: 'kids-friendly',
    name: 'Kids-Friendly Platter',
    description: 'Mild flavors, fun shapes, and dishes kids love to eat.',
    emoji: '🧒',
    bestFor: 4,
    difficulty: 'easy',
    estimatedTime: '45 min',
    dishes: {
      subji: 'Matar Paneer',
      dal: 'Moong Dal',
      rice: 'Peas Pulao',
      bread: 'Plain Paratha',
      sweet: 'Coconut Ladoo',
      drink: 'Mango Lassi',
      side: 'Raita',
    },
  },
  {
    id: 'south-indian',
    name: 'South Indian Platter',
    description: 'Inspired by South Indian flavors with coconut, curry leaves, and tangy notes.',
    emoji: '🌴',
    bestFor: 4,
    difficulty: 'easy',
    estimatedTime: '40 min',
    dishes: {
      subji: 'Bhindi Masala',
      dal: 'Toor Dal',
      rice: 'Lemon Rice',
      bread: 'Roti',
      sweet: 'Rice Kheer',
      drink: 'Buttermilk (Chaas)',
      side: 'Papad',
    },
  },
  {
    id: 'north-indian',
    name: 'North Indian Platter',
    description: 'Classic North Indian thali with rich gravies and aromatic spices.',
    emoji: '🏔️',
    bestFor: 4,
    difficulty: 'medium',
    estimatedTime: '60 min',
    dishes: {
      subji: 'Paneer Butter Masala',
      dal: 'Dal Makhani',
      rice: 'Jeera Rice',
      bread: 'Naan-style Tawa Roti',
      sweet: 'Gajar Halwa',
      drink: 'Buttermilk (Chaas)',
      side: 'Raita',
    },
  },
];
