import type { Recipe } from './types';

export const recipes: Recipe[] = [
  // ===== SUBJI =====
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    category: 'subji',
    baseServings: 4,
    prepTime: '15 min',
    cookTime: '25 min',
    ingredients: [
      { name: 'Paneer', quantity: 400, unit: 'g' },
      { name: 'Tomatoes', quantity: 4, unit: 'medium' },
      { name: 'Cashews', quantity: 15, unit: 'pcs' },
      { name: 'Butter', quantity: 2, unit: 'tbsp' },
      { name: 'Cream', quantity: 3, unit: 'tbsp' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 1, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1.5, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Kasuri methi', quantity: 1, unit: 'tsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 1, unit: 'cup' },
    ],
    instructions: [
      'Cook tomatoes, cashews, ginger, green chili, and spices until soft.',
      'Cool and blend into a smooth gravy.',
      'Heat butter, add cumin and hing.',
      'Add gravy and simmer for 8–10 minutes.',
      'Add paneer, cream, kasuri methi, and garam masala.',
      'Simmer 3–4 minutes and serve hot.',
    ],
    pairings: ['Naan-style Tawa Roti', 'Roti', 'Puri', 'Jeera Rice', 'Peas Pulao', 'Moong Dal', 'Dal Makhani'],
    notes: 'For extra richness, add a dollop of butter on top before serving. Soak cashews in warm water for 10 minutes for smoother gravy.',
    difficulty: 'medium',
  },
  {
    id: 'shahi-paneer',
    name: 'Shahi Paneer',
    category: 'subji',
    baseServings: 4,
    prepTime: '15 min',
    cookTime: '25 min',
    ingredients: [
      { name: 'Paneer', quantity: 400, unit: 'g' },
      { name: 'Tomatoes', quantity: 3, unit: 'medium' },
      { name: 'Cashews', quantity: 12, unit: 'pcs' },
      { name: 'Melon seeds (magaz)', quantity: 1, unit: 'tbsp' },
      { name: 'Cream', quantity: 4, unit: 'tbsp' },
      { name: 'Ghee', quantity: 2, unit: 'tbsp' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Bay leaf', quantity: 1, unit: 'pc' },
      { name: 'Cardamom', quantity: 2, unit: 'pcs' },
      { name: 'Cloves', quantity: 2, unit: 'pcs' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.75, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Sugar', quantity: 0.5, unit: 'tsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 1, unit: 'cup' },
    ],
    instructions: [
      'Soak cashews and melon seeds in warm water for 15 minutes, then grind to a paste.',
      'Blanch tomatoes, peel, and blend to a puree.',
      'Heat ghee, add cumin, bay leaf, cardamom, and cloves.',
      'Add tomato puree, turmeric, red chili, and coriander powder. Cook 8 minutes.',
      'Add cashew-melon paste, sugar, and simmer 5 minutes.',
      'Add paneer cubes, cream, and garam masala. Cook 3–4 minutes.',
      'Garnish with cream and serve hot.',
    ],
    pairings: ['Naan-style Tawa Roti', 'Roti', 'Peas Pulao', 'Jeera Rice'],
    notes: 'Shahi Paneer is richer than regular paneer curry. The melon seeds give it a royal creamy texture.',
    difficulty: 'medium',
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    category: 'subji',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Potato', quantity: 3, unit: 'medium' },
      { name: 'Cauliflower', quantity: 1, unit: 'small head' },
      { name: 'Tomato', quantity: 2, unit: 'medium' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.75, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1.5, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Cut potatoes and cauliflower into bite-sized pieces.',
      'Heat oil, add cumin seeds and hing.',
      'Add ginger and green chili, sauté briefly.',
      'Add potatoes, turmeric, and salt. Cook covered for 5 minutes.',
      'Add cauliflower and all spice powders. Mix gently.',
      'Cook covered on low heat for 12–15 minutes until tender.',
      'Add garam masala, garnish with coriander, and serve.',
    ],
    pairings: ['Roti', 'Puri', 'Moong Dal', 'Toor Dal', 'Plain Rice'],
    notes: 'Do not stir too often to avoid breaking the cauliflower. Sprinkle water if it sticks.',
    difficulty: 'easy',
  },
  {
    id: 'malai-kofta',
    name: 'Malai Kofta',
    category: 'subji',
    baseServings: 4,
    prepTime: '25 min',
    cookTime: '30 min',
    ingredients: [
      { name: 'Paneer (grated)', quantity: 200, unit: 'g' },
      { name: 'Potato (boiled, mashed)', quantity: 2, unit: 'medium' },
      { name: 'Cornflour', quantity: 2, unit: 'tbsp' },
      { name: 'Tomatoes', quantity: 4, unit: 'medium' },
      { name: 'Cashews', quantity: 12, unit: 'pcs' },
      { name: 'Cream', quantity: 3, unit: 'tbsp' },
      { name: 'Butter', quantity: 2, unit: 'tbsp' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 1, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1.5, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Kasuri methi', quantity: 1, unit: 'tsp' },
      { name: 'Sugar', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil (for frying)', quantity: 'as needed', unit: '' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Mix grated paneer, mashed potato, cornflour, and salt. Shape into balls.',
      'Deep fry koftas until golden. Set aside.',
      'Cook tomatoes, cashews, and ginger until soft. Blend smooth.',
      'Heat butter, add cumin and hing. Add gravy and cook 10 minutes.',
      'Add spice powders, cream, sugar, and kasuri methi.',
      'Simmer 5 minutes. Add koftas just before serving.',
    ],
    pairings: ['Naan-style Tawa Roti', 'Jeera Rice', 'Peas Pulao'],
    notes: 'Add koftas to gravy just before serving so they stay firm. You can also bake koftas for a healthier version.',
    difficulty: 'medium',
  },
  {
    id: 'paneer-bhurji',
    name: 'Paneer Bhurji',
    category: 'subji',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '15 min',
    ingredients: [
      { name: 'Paneer (crumbled)', quantity: 400, unit: 'g' },
      { name: 'Tomato', quantity: 2, unit: 'medium' },
      { name: 'Capsicum', quantity: 1, unit: 'medium' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 2, unit: 'pcs' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.25, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Butter', quantity: 1, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Heat butter, add cumin seeds and hing.',
      'Add ginger and green chili, sauté 30 seconds.',
      'Add chopped tomato and capsicum. Cook 3–4 minutes.',
      'Add turmeric, red chili, and coriander powder.',
      'Add crumbled paneer and mix well.',
      'Cook 5 minutes, add garam masala and coriander. Serve hot.',
    ],
    pairings: ['Roti', 'Puri', 'Naan-style Tawa Roti', 'Plain Rice'],
    notes: 'Crumble paneer with hands for best texture. Do not overcook or it becomes dry.',
    difficulty: 'easy',
  },
  {
    id: 'lauki-kofta',
    name: 'Lauki Kofta',
    category: 'subji',
    baseServings: 4,
    prepTime: '20 min',
    cookTime: '25 min',
    ingredients: [
      { name: 'Bottle gourd (lauki, grated)', quantity: 2, unit: 'cups' },
      { name: 'Besan (gram flour)', quantity: 0.5, unit: 'cup' },
      { name: 'Tomatoes', quantity: 3, unit: 'medium' },
      { name: 'Cashews', quantity: 8, unit: 'pcs' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.75, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil', quantity: 'as needed', unit: '' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Squeeze water from grated lauki. Mix with besan, salt, and turmeric.',
      'Shape into small balls and deep fry until golden.',
      'Blend tomatoes, cashews, and ginger into a smooth paste.',
      'Heat oil, add cumin and hing. Add tomato paste and cook 8 minutes.',
      'Add spice powders and simmer 5 minutes.',
      'Add koftas to gravy just before serving.',
    ],
    pairings: ['Roti', 'Jeera Rice', 'Moong Dal'],
    notes: 'Squeeze lauki well or koftas will break while frying. Add koftas at the end to keep them firm.',
    difficulty: 'medium',
  },
  {
    id: 'bhindi-masala',
    name: 'Bhindi Masala',
    category: 'subji',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '15 min',
    ingredients: [
      { name: 'Bhindi (okra)', quantity: 500, unit: 'g' },
      { name: 'Tomato', quantity: 1, unit: 'medium' },
      { name: 'Ginger', quantity: 0.5, unit: 'inch' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.25, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Amchur (dry mango powder)', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil', quantity: 3, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Wash bhindi and dry completely. Cut into 1-inch pieces.',
      'Heat oil, add cumin and hing.',
      'Add bhindi and sauté on medium-high heat for 8–10 minutes without stirring too much.',
      'Add all spice powders and tomato. Cook 3 minutes.',
      'Add amchur, mix well, and serve.',
    ],
    pairings: ['Roti', 'Plain Rice', 'Toor Dal'],
    notes: 'Bhindi must be completely dry before cutting to avoid sliminess. Do not cover while cooking.',
    difficulty: 'easy',
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    category: 'subji',
    baseServings: 4,
    prepTime: '15 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Paneer', quantity: 300, unit: 'g' },
      { name: 'Spinach (palak)', quantity: 3, unit: 'cups packed' },
      { name: 'Tomato', quantity: 1, unit: 'medium' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 2, unit: 'pcs' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Cream', quantity: 2, unit: 'tbsp' },
      { name: 'Butter', quantity: 1.5, unit: 'tbsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Blanch spinach in boiling water for 2 minutes. Transfer to ice water.',
      'Blend spinach, tomato, ginger, and green chili into a smooth puree.',
      'Heat butter, add cumin and hing.',
      'Add spinach puree and cook 8–10 minutes.',
      'Add paneer cubes, cream, and garam masala.',
      'Simmer 3 minutes and serve hot.',
    ],
    pairings: ['Roti', 'Naan-style Tawa Roti', 'Jeera Rice', 'Moong Dal'],
    notes: 'Blanching and ice bath keeps spinach bright green. Do not overcook the puree.',
    difficulty: 'easy',
  },
  {
    id: 'matar-paneer',
    name: 'Matar Paneer',
    category: 'subji',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Paneer', quantity: 300, unit: 'g' },
      { name: 'Green peas', quantity: 1, unit: 'cup' },
      { name: 'Tomatoes', quantity: 3, unit: 'medium' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.75, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Blend tomatoes into a puree.',
      'Heat oil, add cumin and hing.',
      'Add ginger, green chili, and tomato puree. Cook 8 minutes.',
      'Add turmeric, red chili, and coriander powder.',
      'Add peas and cook 5 minutes.',
      'Add paneer cubes and garam masala. Simmer 3 minutes.',
      'Garnish with coriander and serve.',
    ],
    pairings: ['Roti', 'Puri', 'Jeera Rice', 'Plain Rice'],
    notes: 'Use fresh or frozen peas. Add paneer at the end so it stays soft.',
    difficulty: 'easy',
  },
  {
    id: 'aloo-matar',
    name: 'Aloo Matar',
    category: 'subji',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Potato', quantity: 3, unit: 'medium' },
      { name: 'Green peas', quantity: 0.75, unit: 'cup' },
      { name: 'Tomato', quantity: 2, unit: 'medium' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.75, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Cut potatoes into cubes.',
      'Heat oil, add cumin and hing.',
      'Add ginger, then potatoes with turmeric and salt. Cook 5 minutes covered.',
      'Add chopped tomatoes and spice powders. Cook 5 minutes.',
      'Add peas and cook covered until potatoes are tender (8–10 min).',
      'Add garam masala and coriander. Serve hot.',
    ],
    pairings: ['Roti', 'Puri', 'Plain Rice', 'Moong Dal'],
    notes: 'A simple everyday sabji. Add a splash of water if it gets too dry.',
    difficulty: 'easy',
  },
  // ===== DAL =====
  {
    id: 'moong-dal',
    name: 'Moong Dal',
    category: 'dal',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Moong dal (yellow)', quantity: 1, unit: 'cup' },
      { name: 'Tomato', quantity: 1, unit: 'medium' },
      { name: 'Ginger', quantity: 0.5, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Ghee', quantity: 1, unit: 'tbsp' },
      { name: 'Curry leaves', quantity: 5, unit: 'pcs' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Lemon juice', quantity: 1, unit: 'tsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 2.5, unit: 'cups' },
    ],
    instructions: [
      'Wash moong dal and pressure cook with water, turmeric, and salt for 3 whistles.',
      'Mash dal lightly with a spoon.',
      'Heat ghee, add cumin, hing, and curry leaves.',
      'Add chopped tomato, ginger, and green chili. Cook 3 minutes.',
      'Add cooked dal, mix well, and simmer 5 minutes.',
      'Add lemon juice and coriander. Serve hot.',
    ],
    pairings: ['Plain Rice', 'Jeera Rice', 'Roti', 'Aloo Gobi'],
    notes: 'Moong dal is light and easy to digest. Adjust water for desired consistency.',
    difficulty: 'easy',
  },
  {
    id: 'toor-dal',
    name: 'Toor Dal',
    category: 'dal',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '25 min',
    ingredients: [
      { name: 'Toor dal', quantity: 1, unit: 'cup' },
      { name: 'Tomato', quantity: 1, unit: 'medium' },
      { name: 'Ginger', quantity: 0.5, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Mustard seeds', quantity: 0.5, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Ghee', quantity: 1, unit: 'tbsp' },
      { name: 'Curry leaves', quantity: 5, unit: 'pcs' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Wash toor dal and pressure cook with water, turmeric, and salt for 4 whistles.',
      'Mash dal well.',
      'Heat ghee, add mustard seeds, cumin, hing, and curry leaves.',
      'Add tomato, ginger, green chili, and red chili powder. Cook 3 minutes.',
      'Add cooked dal, adjust consistency with water, and simmer 5 minutes.',
      'Garnish with coriander and serve.',
    ],
    pairings: ['Plain Rice', 'Jeera Rice', 'Roti', 'Aloo Gobi'],
    notes: 'Toor dal thickens as it cools. Add extra water if reheating.',
    difficulty: 'easy',
  },
  {
    id: 'chana-dal',
    name: 'Chana Dal',
    category: 'dal',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '30 min',
    ingredients: [
      { name: 'Chana dal', quantity: 1, unit: 'cup' },
      { name: 'Tomato', quantity: 1, unit: 'medium' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.75, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Ghee', quantity: 1.5, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Soak chana dal for 30 minutes. Pressure cook with water, turmeric, and salt for 5 whistles.',
      'Heat ghee, add cumin and hing.',
      'Add ginger, green chili, and tomato. Cook 4 minutes.',
      'Add red chili and coriander powder. Cook 2 minutes.',
      'Add cooked dal, garam masala, and simmer 5–7 minutes.',
      'Garnish with coriander and serve.',
    ],
    pairings: ['Plain Rice', 'Jeera Rice', 'Roti', 'Puri'],
    notes: 'Soaking chana dal reduces cooking time. It should be cooked but not mushy.',
    difficulty: 'easy',
  },
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    category: 'dal',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '40 min',
    ingredients: [
      { name: 'Whole urad dal', quantity: 0.75, unit: 'cup' },
      { name: 'Rajma (kidney beans)', quantity: 0.25, unit: 'cup' },
      { name: 'Tomato puree', quantity: 1, unit: 'cup' },
      { name: 'Butter', quantity: 3, unit: 'tbsp' },
      { name: 'Cream', quantity: 3, unit: 'tbsp' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 1, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Kasuri methi', quantity: 1, unit: 'tsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Soak urad dal and rajma overnight. Pressure cook with water and salt for 6–7 whistles.',
      'Heat butter, add cumin, hing, ginger, and green chili.',
      'Add tomato puree, turmeric, red chili, and coriander powder. Cook 10 minutes.',
      'Add cooked dal and simmer on low heat for 20 minutes, stirring occasionally.',
      'Add cream, kasuri methi, garam masala, and butter.',
      'Simmer 5 more minutes and serve hot.',
    ],
    pairings: ['Naan-style Tawa Roti', 'Jeera Rice', 'Paneer Butter Masala', 'Roti'],
    notes: 'Slow cooking on low heat is the secret to creamy dal makhani. The longer it simmers, the better it tastes.',
    difficulty: 'medium',
  },
  {
    id: 'rajma',
    name: 'Rajma',
    category: 'dal',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '35 min',
    ingredients: [
      { name: 'Rajma (kidney beans)', quantity: 1, unit: 'cup' },
      { name: 'Tomato', quantity: 3, unit: 'medium' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 1, unit: 'tsp' },
      { name: 'Coriander powder', quantity: 1.5, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.75, unit: 'tsp' },
      { name: 'Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Soak rajma overnight. Pressure cook with water and salt for 7–8 whistles until soft.',
      'Blend tomatoes into a puree.',
      'Heat oil, add cumin and hing.',
      'Add ginger, green chili, and tomato puree. Cook 8–10 minutes.',
      'Add spice powders and cook 2 minutes.',
      'Add cooked rajma with its water. Simmer 15 minutes.',
      'Mash a few beans for thickness. Add garam masala and coriander.',
    ],
    pairings: ['Plain Rice', 'Jeera Rice'],
    notes: 'Rajma must be soaked overnight and cooked until completely soft.',
    difficulty: 'medium',
  },
  // ===== RICE =====
  {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    category: 'rice',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Basmati rice', quantity: 1.5, unit: 'cups' },
      { name: 'Cumin seeds', quantity: 1.5, unit: 'tsp' },
      { name: 'Ghee', quantity: 1.5, unit: 'tbsp' },
      { name: 'Bay leaf', quantity: 1, unit: 'pc' },
      { name: 'Cloves', quantity: 2, unit: 'pcs' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Wash and soak rice for 20 minutes. Drain.',
      'Heat ghee, add cumin seeds, bay leaf, and cloves.',
      'When cumin splutters, add rice and sauté 1 minute.',
      'Add water and salt. Bring to boil.',
      'Cover and cook on low heat for 12–15 minutes.',
      'Fluff with fork and serve.',
    ],
    pairings: ['Paneer Butter Masala', 'Shahi Paneer', 'Malai Kofta', 'Dal Makhani', 'Rajma', 'Chana Dal'],
    notes: 'Soaking rice gives longer, fluffier grains. Use 1:2 rice to water ratio.',
    difficulty: 'easy',
  },
  {
    id: 'peas-pulao',
    name: 'Peas Pulao',
    category: 'rice',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Basmati rice', quantity: 1.5, unit: 'cups' },
      { name: 'Green peas', quantity: 0.75, unit: 'cup' },
      { name: 'Ghee', quantity: 1.5, unit: 'tbsp' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Bay leaf', quantity: 1, unit: 'pc' },
      { name: 'Cardamom', quantity: 2, unit: 'pcs' },
      { name: 'Cloves', quantity: 2, unit: 'pcs' },
      { name: 'Cinnamon', quantity: 1, unit: 'inch' },
      { name: 'Ginger', quantity: 0.5, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Wash and soak rice for 20 minutes.',
      'Heat ghee, add cumin, bay leaf, cardamom, cloves, and cinnamon.',
      'Add ginger and green chili, sauté briefly.',
      'Add peas and rice, sauté 1 minute.',
      'Add water and salt. Bring to boil.',
      'Cover and cook on low heat for 12–15 minutes.',
      'Let rest 5 minutes, fluff and serve.',
    ],
    pairings: ['Paneer Butter Masala', 'Shahi Paneer', 'Malai Kofta', 'Moong Dal'],
    notes: 'Use fresh or frozen peas. Frozen peas can be added directly without thawing.',
    difficulty: 'easy',
  },
  {
    id: 'vegetable-pulao',
    name: 'Vegetable Pulao',
    category: 'rice',
    baseServings: 4,
    prepTime: '15 min',
    cookTime: '25 min',
    ingredients: [
      { name: 'Basmati rice', quantity: 1.5, unit: 'cups' },
      { name: 'Mixed vegetables (carrot, beans, peas, corn)', quantity: 1.5, unit: 'cups' },
      { name: 'Ghee', quantity: 2, unit: 'tbsp' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Bay leaf', quantity: 1, unit: 'pc' },
      { name: 'Cardamom', quantity: 2, unit: 'pcs' },
      { name: 'Cloves', quantity: 3, unit: 'pcs' },
      { name: 'Cinnamon', quantity: 1, unit: 'inch' },
      { name: 'Ginger', quantity: 1, unit: 'inch' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Turmeric', quantity: 0.25, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Wash and soak rice for 20 minutes.',
      'Heat ghee, add whole spices (cumin, bay leaf, cardamom, cloves, cinnamon).',
      'Add ginger and green chili, sauté 30 seconds.',
      'Add vegetables and turmeric. Sauté 3 minutes.',
      'Add drained rice, water, and salt. Bring to boil.',
      'Cover and cook on low heat for 12–15 minutes.',
      'Add garam masala, fluff gently, and garnish with coriander.',
    ],
    pairings: ['Moong Dal', 'Toor Dal', 'Paneer Bhurji'],
    notes: 'Cut all vegetables to similar size for even cooking.',
    difficulty: 'easy',
  },
  {
    id: 'plain-rice',
    name: 'Plain Rice',
    category: 'rice',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '15 min',
    ingredients: [
      { name: 'Basmati rice', quantity: 1.5, unit: 'cups' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 3, unit: 'cups' },
    ],
    instructions: [
      'Wash rice 2–3 times until water runs clear.',
      'Soak for 20 minutes (optional but recommended).',
      'Add rice, water, and salt to a pot. Bring to boil.',
      'Reduce heat to low, cover, and cook 12 minutes.',
      'Turn off heat and let rest 5 minutes.',
      'Fluff with fork and serve.',
    ],
    pairings: ['Rajma', 'Moong Dal', 'Toor Dal', 'Chana Dal', 'Aloo Gobi'],
    notes: 'For best results, use aged basmati rice. The 1:2 ratio works for most basmati varieties.',
    difficulty: 'easy',
  },
  {
    id: 'lemon-rice',
    name: 'Lemon Rice',
    category: 'rice',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '10 min',
    ingredients: [
      { name: 'Cooked rice', quantity: 3, unit: 'cups' },
      { name: 'Lemon juice', quantity: 3, unit: 'tbsp' },
      { name: 'Mustard seeds', quantity: 1, unit: 'tsp' },
      { name: 'Cumin seeds', quantity: 0.5, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.5, unit: 'tsp' },
      { name: 'Green chili', quantity: 2, unit: 'pcs' },
      { name: 'Curry leaves', quantity: 8, unit: 'pcs' },
      { name: 'Peanuts', quantity: 2, unit: 'tbsp' },
      { name: 'Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Heat oil, add mustard seeds and let them splutter.',
      'Add cumin, hing, curry leaves, green chili, and peanuts.',
      'Fry peanuts until golden (2 minutes).',
      'Add turmeric and mix.',
      'Add cooked rice and lemon juice. Toss gently.',
      'Serve warm or at room temperature.',
    ],
    pairings: ['Papad', 'Raita'],
    notes: 'Use day-old rice for best results. Add lemon juice off the heat to preserve freshness.',
    difficulty: 'easy',
  },
  {
    id: 'curd-rice',
    name: 'Curd Rice',
    category: 'rice',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '5 min',
    ingredients: [
      { name: 'Cooked rice', quantity: 2, unit: 'cups' },
      { name: 'Yogurt', quantity: 1.5, unit: 'cups' },
      { name: 'Milk', quantity: 0.25, unit: 'cup' },
      { name: 'Mustard seeds', quantity: 0.5, unit: 'tsp' },
      { name: 'Cumin seeds', quantity: 0.5, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Curry leaves', quantity: 5, unit: 'pcs' },
      { name: 'Green chili', quantity: 1, unit: 'pc' },
      { name: 'Ginger', quantity: 0.5, unit: 'inch' },
      { name: 'Oil', quantity: 1, unit: 'tsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Mash cooked rice slightly. Mix with yogurt, milk, and salt.',
      'Heat oil, add mustard seeds and let them splutter.',
      'Add cumin, hing, curry leaves, ginger, and green chili.',
      'Pour tempering over rice-yogurt mixture.',
      'Mix well and serve chilled or at room temperature.',
    ],
    pairings: ['Papad', 'Lemon Rice'],
    notes: 'Curd rice thickens as it sits. Add more milk or yogurt before serving if needed.',
    difficulty: 'easy',
  },
  // ===== BREAD =====
  {
    id: 'puri',
    name: 'Puri',
    category: 'bread',
    baseServings: 4,
    prepTime: '15 min',
    cookTime: '15 min',
    ingredients: [
      { name: 'Whole wheat flour', quantity: 2, unit: 'cups' },
      { name: 'Salt', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil (for dough)', quantity: 1, unit: 'tbsp' },
      { name: 'Water', quantity: 0.75, unit: 'cup' },
      { name: 'Oil (for frying)', quantity: 'as needed', unit: '' },
    ],
    instructions: [
      'Mix flour, salt, and 1 tbsp oil.',
      'Add water gradually and knead into a firm dough.',
      'Rest dough for 10 minutes.',
      'Divide into small balls and roll into thin circles.',
      'Heat oil for deep frying. Oil should be hot enough.',
      'Slide puri in and press gently. It will puff up.',
      'Flip and fry other side. Drain on paper towel.',
    ],
    pairings: ['Aloo Gobi', 'Paneer Butter Masala', 'Suji Halwa', 'Chana Dal'],
    notes: 'Dough should be firm, not soft. Oil must be hot enough or puris won\'t puff.',
    difficulty: 'medium',
  },
  {
    id: 'roti',
    name: 'Roti',
    category: 'bread',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '15 min',
    ingredients: [
      { name: 'Whole wheat flour', quantity: 2, unit: 'cups' },
      { name: 'Salt', quantity: 0.5, unit: 'tsp' },
      { name: 'Water', quantity: 0.75, unit: 'cup' },
      { name: 'Ghee (for serving)', quantity: 1, unit: 'tbsp' },
    ],
    instructions: [
      'Mix flour and salt. Add water gradually.',
      'Knead into a soft, smooth dough for 5 minutes.',
      'Rest covered for 10 minutes.',
      'Divide into balls, dust with flour, and roll into thin circles.',
      'Heat tawa on medium-high. Place roti and cook until bubbles appear.',
      'Flip and cook other side. Press gently with cloth for puffing.',
      'Apply ghee and serve hot.',
    ],
    pairings: ['Paneer Butter Masala', 'Shahi Paneer', 'Aloo Gobi', 'Dal Makhani', 'Moong Dal'],
    notes: 'Soft dough makes soft rotis. Let dough rest for best results.',
    difficulty: 'easy',
  },
  {
    id: 'naan-tawa-roti',
    name: 'Naan-style Tawa Roti',
    category: 'bread',
    baseServings: 4,
    prepTime: '15 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'All-purpose flour (maida)', quantity: 2, unit: 'cups' },
      { name: 'Yogurt', quantity: 3, unit: 'tbsp' },
      { name: 'Baking soda', quantity: 0.25, unit: 'tsp' },
      { name: 'Sugar', quantity: 0.5, unit: 'tsp' },
      { name: 'Salt', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil', quantity: 1, unit: 'tbsp' },
      { name: 'Water', quantity: 0.5, unit: 'cup' },
      { name: 'Butter', quantity: 2, unit: 'tbsp' },
      { name: 'Nigella seeds (kalonji)', quantity: 0.5, unit: 'tsp' },
    ],
    instructions: [
      'Mix flour, baking soda, sugar, and salt.',
      'Add yogurt, oil, and water. Knead into soft dough.',
      'Rest covered for 1 hour.',
      'Divide into balls, roll into oval/teardrop shapes.',
      'Sprinkle nigella seeds and press gently.',
      'Cook on hot tawa, flip when bubbles form.',
      'Hold with tongs over direct flame briefly for char marks.',
      'Brush with butter and serve.',
    ],
    pairings: ['Paneer Butter Masala', 'Shahi Paneer', 'Malai Kofta', 'Dal Makhani'],
    notes: 'Resting the dough is important for soft naan.',
    difficulty: 'medium',
  },
  {
    id: 'paratha',
    name: 'Plain Paratha',
    category: 'bread',
    baseServings: 4,
    prepTime: '15 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Whole wheat flour', quantity: 2, unit: 'cups' },
      { name: 'Salt', quantity: 0.5, unit: 'tsp' },
      { name: 'Water', quantity: 0.75, unit: 'cup' },
      { name: 'Ghee', quantity: 3, unit: 'tbsp' },
    ],
    instructions: [
      'Mix flour and salt. Add water and knead into soft dough.',
      'Rest for 15 minutes.',
      'Divide into balls. Roll each into a circle.',
      'Apply ghee, fold into triangle or square, roll again.',
      'Cook on hot tawa with ghee on both sides until golden.',
      'Serve hot with curry or yogurt.',
    ],
    pairings: ['Paneer Bhurji', 'Aloo Gobi', 'Moong Dal', 'Raita'],
    notes: 'Layering with ghee creates flaky texture. Cook on medium heat for even browning.',
    difficulty: 'easy',
  },
  // ===== SWEET =====
  {
    id: 'suji-halwa',
    name: 'Suji Halwa',
    category: 'sweet',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '15 min',
    ingredients: [
      { name: 'Suji (semolina)', quantity: 1, unit: 'cup' },
      { name: 'Ghee', quantity: 0.5, unit: 'cup' },
      { name: 'Sugar', quantity: 0.75, unit: 'cup' },
      { name: 'Water', quantity: 2, unit: 'cups' },
      { name: 'Cardamom powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Cashews', quantity: 8, unit: 'pcs' },
      { name: 'Raisins', quantity: 10, unit: 'pcs' },
    ],
    instructions: [
      'Heat ghee in a pan. Fry cashews and raisins, set aside.',
      'In same ghee, roast suji on medium heat until golden and fragrant (5–7 min).',
      'Boil water with sugar separately until sugar dissolves.',
      'Slowly add sugar water to roasted suji (careful, it splutters).',
      'Stir continuously until mixture thickens and leaves the pan.',
      'Add cardamom, cashews, and raisins. Serve warm.',
    ],
    pairings: ['Puri', 'Plain Rice'],
    notes: 'Roast suji on low-medium heat patiently for best flavor.',
    difficulty: 'easy',
  },
  {
    id: 'rice-kheer',
    name: 'Rice Kheer',
    category: 'sweet',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '35 min',
    ingredients: [
      { name: 'Rice', quantity: 0.25, unit: 'cup' },
      { name: 'Full-fat milk', quantity: 4, unit: 'cups' },
      { name: 'Sugar', quantity: 0.5, unit: 'cup' },
      { name: 'Cardamom powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Saffron strands', quantity: 5, unit: 'pcs' },
      { name: 'Cashews', quantity: 6, unit: 'pcs' },
      { name: 'Raisins', quantity: 8, unit: 'pcs' },
      { name: 'Almonds (sliced)', quantity: 6, unit: 'pcs' },
    ],
    instructions: [
      'Wash and soak rice for 20 minutes.',
      'Boil milk in a heavy-bottom pan on medium heat.',
      'Add drained rice and cook on low heat, stirring often (20–25 min).',
      'When rice is fully cooked and milk thickens, add sugar.',
      'Add cardamom, saffron, cashews, raisins, and almonds.',
      'Cook 5 more minutes. Serve warm or chilled.',
    ],
    pairings: [],
    notes: 'Stir frequently to prevent milk from sticking. Kheer thickens as it cools.',
    difficulty: 'easy',
  },
  {
    id: 'coconut-ladoo',
    name: 'Coconut Ladoo',
    category: 'sweet',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '15 min',
    ingredients: [
      { name: 'Desiccated coconut', quantity: 2, unit: 'cups' },
      { name: 'Condensed milk', quantity: 0.75, unit: 'cup' },
      { name: 'Cardamom powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Ghee', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Grease your palms with a little ghee.',
      'Mix coconut and condensed milk in a pan on low heat.',
      'Stir continuously for 8–10 minutes until mixture thickens.',
      'Add cardamom powder and mix well.',
      'Let cool slightly until you can handle it.',
      'Shape into small round balls (ladoos).',
      'Roll in extra coconut if desired. Let set for 30 minutes.',
    ],
    pairings: [],
    notes: 'Do not overcook or ladoos will become hard. They firm up as they cool.',
    difficulty: 'easy',
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun (Ready Mix)',
    category: 'sweet',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '25 min',
    ingredients: [
      { name: 'Gulab jamun ready mix', quantity: 1, unit: 'cup' },
      { name: 'Milk', quantity: 0.25, unit: 'cup' },
      { name: 'Ghee', quantity: 1, unit: 'tsp' },
      { name: 'Sugar', quantity: 1.5, unit: 'cups' },
      { name: 'Water', quantity: 1.5, unit: 'cups' },
      { name: 'Cardamom powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Rose water', quantity: 1, unit: 'tsp' },
      { name: 'Oil (for frying)', quantity: 'as needed', unit: '' },
    ],
    instructions: [
      'Make sugar syrup: boil sugar and water until slightly sticky. Add cardamom and rose water.',
      'Mix ready mix with milk and ghee. Knead gently into smooth dough.',
      'Make small smooth balls without cracks.',
      'Heat oil on low-medium heat. Fry balls slowly until deep brown (7–8 min).',
      'Drop hot gulab jamuns into warm sugar syrup.',
      'Let soak for at least 1 hour before serving.',
    ],
    pairings: [],
    notes: 'Fry on LOW heat only. High heat will cook outside but leave inside raw.',
    difficulty: 'medium',
  },
  {
    id: 'gajar-halwa',
    name: 'Gajar Halwa',
    category: 'sweet',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '30 min',
    ingredients: [
      { name: 'Carrots (grated)', quantity: 3, unit: 'cups' },
      { name: 'Full-fat milk', quantity: 2, unit: 'cups' },
      { name: 'Sugar', quantity: 0.5, unit: 'cup' },
      { name: 'Ghee', quantity: 3, unit: 'tbsp' },
      { name: 'Cardamom powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Cashews', quantity: 8, unit: 'pcs' },
      { name: 'Raisins', quantity: 10, unit: 'pcs' },
      { name: 'Khoya (optional)', quantity: 0.25, unit: 'cup' },
    ],
    instructions: [
      'Heat ghee, fry cashews and raisins. Set aside.',
      'Add grated carrots and sauté 5 minutes.',
      'Add milk and cook on medium heat until milk is absorbed (15–20 min).',
      'Add sugar and cook until dry.',
      'Add khoya (if using), cardamom, and dry fruits.',
      'Serve warm.',
    ],
    pairings: [],
    notes: 'Use red carrots (winter variety) for best color and sweetness. Stir often to prevent burning.',
    difficulty: 'easy',
  },
  // ===== SNACKS =====
  {
    id: 'samosa',
    name: 'Aloo Samosa',
    category: 'snack',
    baseServings: 4,
    prepTime: '25 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'All-purpose flour (maida)', quantity: 1.5, unit: 'cups' },
      { name: 'Potato (boiled, mashed)', quantity: 3, unit: 'medium' },
      { name: 'Green peas', quantity: 0.5, unit: 'cup' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Ginger', quantity: 0.5, unit: 'inch' },
      { name: 'Green chili', quantity: 2, unit: 'pcs' },
      { name: 'Coriander powder', quantity: 1, unit: 'tsp' },
      { name: 'Garam masala', quantity: 0.5, unit: 'tsp' },
      { name: 'Amchur', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil (for dough)', quantity: 3, unit: 'tbsp' },
      { name: 'Oil (for frying)', quantity: 'as needed', unit: '' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Make dough: mix flour, 3 tbsp oil, salt, and water. Knead firm. Rest 20 min.',
      'For filling: heat oil, add cumin, ginger, green chili.',
      'Add peas, mashed potato, and all spices. Mix well. Cool.',
      'Roll dough into ovals, cut in half. Form cones and fill.',
      'Seal edges with water.',
      'Deep fry on medium-low heat until golden and crispy.',
    ],
    pairings: ['Nimbu Pani (Lemonade)', 'Mint Chutney'],
    notes: 'Fry on medium-low heat for crispy layers. High heat makes them soft.',
    difficulty: 'medium',
  },
  {
    id: 'dhokla',
    name: 'Besan Dhokla',
    category: 'snack',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Besan (gram flour)', quantity: 1, unit: 'cup' },
      { name: 'Yogurt', quantity: 0.5, unit: 'cup' },
      { name: 'Water', quantity: 0.25, unit: 'cup' },
      { name: 'Eno fruit salt', quantity: 1, unit: 'tsp' },
      { name: 'Turmeric', quantity: 0.25, unit: 'tsp' },
      { name: 'Sugar', quantity: 1, unit: 'tsp' },
      { name: 'Mustard seeds', quantity: 1, unit: 'tsp' },
      { name: 'Curry leaves', quantity: 6, unit: 'pcs' },
      { name: 'Green chili', quantity: 2, unit: 'pcs' },
      { name: 'Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Lemon juice', quantity: 1, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Mix besan, yogurt, water, turmeric, sugar, and salt into smooth batter.',
      'Add Eno and lemon juice. Mix quickly.',
      'Pour into greased plate and steam for 15 minutes.',
      'For tempering: heat oil, add mustard seeds, curry leaves, green chili.',
      'Cut dhokla into pieces and pour tempering over.',
      'Garnish with coriander and serve.',
    ],
    pairings: ['Nimbu Pani (Lemonade)', 'Mint Chutney'],
    notes: 'Add Eno just before steaming. Do not over-mix after adding Eno.',
    difficulty: 'easy',
  },
  {
    id: 'khandvi',
    name: 'Khandvi',
    category: 'snack',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '15 min',
    ingredients: [
      { name: 'Besan (gram flour)', quantity: 0.5, unit: 'cup' },
      { name: 'Yogurt', quantity: 0.5, unit: 'cup' },
      { name: 'Water', quantity: 0.5, unit: 'cup' },
      { name: 'Turmeric', quantity: 0.25, unit: 'tsp' },
      { name: 'Ginger paste', quantity: 1, unit: 'tsp' },
      { name: 'Mustard seeds', quantity: 0.5, unit: 'tsp' },
      { name: 'Sesame seeds', quantity: 1, unit: 'tsp' },
      { name: 'Curry leaves', quantity: 5, unit: 'pcs' },
      { name: 'Desiccated coconut', quantity: 2, unit: 'tbsp' },
      { name: 'Oil', quantity: 1, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Mix besan, yogurt, water, turmeric, ginger paste, and salt.',
      'Cook on medium heat, stirring continuously for 8–10 minutes until thick.',
      'Spread thin on greased surface (back of thali works well).',
      'Let cool 5 minutes, then roll into tight rolls.',
      'For tempering: heat oil, add mustard seeds, sesame seeds, curry leaves.',
      'Pour over rolls. Garnish with coconut and coriander.',
    ],
    pairings: ['Nimbu Pani (Lemonade)'],
    notes: 'Stir continuously to avoid lumps. Spread very thin for easy rolling.',
    difficulty: 'medium',
  },
  {
    id: 'poha',
    name: 'Poha',
    category: 'snack',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '10 min',
    ingredients: [
      { name: 'Flattened rice (poha)', quantity: 2, unit: 'cups' },
      { name: 'Potato', quantity: 1, unit: 'medium' },
      { name: 'Peanuts', quantity: 2, unit: 'tbsp' },
      { name: 'Mustard seeds', quantity: 0.5, unit: 'tsp' },
      { name: 'Cumin seeds', quantity: 0.5, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Turmeric', quantity: 0.25, unit: 'tsp' },
      { name: 'Green chili', quantity: 2, unit: 'pcs' },
      { name: 'Curry leaves', quantity: 5, unit: 'pcs' },
      { name: 'Lemon juice', quantity: 1, unit: 'tbsp' },
      { name: 'Oil', quantity: 2, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Sugar', quantity: 0.5, unit: 'tsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Rinse poha in water, drain, and set aside.',
      'Heat oil, add mustard seeds, cumin, hing, and curry leaves.',
      'Add peanuts and fry until golden.',
      'Add diced potato and cook until soft (5 min).',
      'Add green chili, turmeric, sugar, and salt.',
      'Add poha, mix gently, and cook 2 minutes.',
      'Add lemon juice and coriander. Serve warm.',
    ],
    pairings: ['Buttermilk (Chaas)', 'Nimbu Pani (Lemonade)'],
    notes: 'Do not soak poha too long or it becomes mushy. Just rinse and drain.',
    difficulty: 'easy',
  },
  // ===== SIDES =====
  {
    id: 'raita',
    name: 'Raita',
    category: 'side',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: [
      { name: 'Yogurt', quantity: 1.5, unit: 'cups' },
      { name: 'Cucumber (grated)', quantity: 0.5, unit: 'cup' },
      { name: 'Cumin powder (roasted)', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.25, unit: 'tsp' },
      { name: 'Fresh coriander', quantity: 1, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Whisk yogurt until smooth.',
      'Add grated cucumber and mix.',
      'Add roasted cumin powder, red chili powder, and salt.',
      'Garnish with coriander.',
      'Serve chilled.',
    ],
    pairings: ['Jeera Rice', 'Vegetable Pulao', 'Plain Paratha'],
    notes: 'Squeeze excess water from cucumber for thicker raita. Serve cold.',
    difficulty: 'easy',
  },
  {
    id: 'papad',
    name: 'Papad',
    category: 'side',
    baseServings: 4,
    prepTime: '1 min',
    cookTime: '2 min',
    ingredients: [
      { name: 'Papad', quantity: 4, unit: 'pcs' },
      { name: 'Oil (if frying)', quantity: 'as needed', unit: '' },
    ],
    instructions: [
      'Option 1: Roast directly over gas flame, turning with tongs.',
      'Option 2: Microwave for 30–40 seconds.',
      'Option 3: Deep fry in hot oil for 5 seconds each side.',
      'Serve immediately.',
    ],
    pairings: ['Plain Rice', 'Rajma', 'Moong Dal'],
    notes: 'Roasted papad is healthier. Fried papad is crispier. Serve immediately as it softens quickly.',
    difficulty: 'easy',
  },
  {
    id: 'mint-chutney',
    name: 'Mint Chutney',
    category: 'side',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: [
      { name: 'Fresh mint leaves', quantity: 1, unit: 'cup packed' },
      { name: 'Fresh coriander', quantity: 0.5, unit: 'cup' },
      { name: 'Green chili', quantity: 2, unit: 'pcs' },
      { name: 'Ginger', quantity: 0.5, unit: 'inch' },
      { name: 'Lemon juice', quantity: 2, unit: 'tbsp' },
      { name: 'Cumin powder', quantity: 0.5, unit: 'tsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
      { name: 'Water', quantity: 2, unit: 'tbsp' },
    ],
    instructions: [
      'Wash mint and coriander leaves.',
      'Add all ingredients to a blender.',
      'Blend into a smooth paste, adding minimal water.',
      'Adjust salt and lemon juice to taste.',
      'Serve fresh with snacks or meals.',
    ],
    pairings: ['Aloo Samosa', 'Besan Dhokla', 'Roti'],
    notes: 'Use immediately for best color. Stays fresh in fridge for 2–3 days.',
    difficulty: 'easy',
  },
  {
    id: 'pickle-instant',
    name: 'Instant Lemon Pickle',
    category: 'side',
    baseServings: 4,
    prepTime: '10 min',
    cookTime: '0 min',
    ingredients: [
      { name: 'Lemon', quantity: 2, unit: 'medium' },
      { name: 'Salt', quantity: 1, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 1, unit: 'tsp' },
      { name: 'Turmeric', quantity: 0.25, unit: 'tsp' },
      { name: 'Mustard oil', quantity: 1, unit: 'tbsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
    ],
    instructions: [
      'Cut lemons into small pieces, remove seeds.',
      'Mix with salt, red chili powder, turmeric, and hing.',
      'Add mustard oil and mix well.',
      'Let sit for 30 minutes before serving.',
      'Store in glass jar.',
    ],
    pairings: ['Roti', 'Plain Rice', 'Plain Paratha'],
    notes: 'Tastes better the next day. Use clean, dry spoon always.',
    difficulty: 'easy',
  },
  // ===== DRINKS =====
  {
    id: 'buttermilk',
    name: 'Buttermilk (Chaas)',
    category: 'drink',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: [
      { name: 'Yogurt', quantity: 1, unit: 'cup' },
      { name: 'Water', quantity: 3, unit: 'cups' },
      { name: 'Cumin powder (roasted)', quantity: 0.5, unit: 'tsp' },
      { name: 'Hing', quantity: 1, unit: 'pinch' },
      { name: 'Ginger', quantity: 0.25, unit: 'inch' },
      { name: 'Curry leaves', quantity: 3, unit: 'pcs' },
      { name: 'Fresh coriander', quantity: 1, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Whisk yogurt until smooth.',
      'Add cold water and whisk well.',
      'Add roasted cumin, hing, grated ginger, and salt.',
      'Garnish with curry leaves and coriander.',
      'Serve chilled.',
    ],
    pairings: ['Poha', 'Plain Rice', 'Roti'],
    notes: 'Great for digestion. Serve cold in summer. Add ice if desired.',
    difficulty: 'easy',
  },
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    category: 'drink',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: [
      { name: 'Mango pulp', quantity: 1, unit: 'cup' },
      { name: 'Yogurt', quantity: 1, unit: 'cup' },
      { name: 'Milk', quantity: 0.5, unit: 'cup' },
      { name: 'Sugar', quantity: 2, unit: 'tbsp' },
      { name: 'Cardamom powder', quantity: 0.25, unit: 'tsp' },
      { name: 'Ice cubes', quantity: 4, unit: 'pcs' },
    ],
    instructions: [
      'Add mango pulp, yogurt, milk, sugar, and cardamom to blender.',
      'Add ice cubes.',
      'Blend until smooth and frothy.',
      'Pour into glasses and serve immediately.',
    ],
    pairings: [],
    notes: 'Use ripe Alphonso mangoes for best flavor. Adjust sugar based on mango sweetness.',
    difficulty: 'easy',
  },
  {
    id: 'thandai',
    name: 'Thandai',
    category: 'drink',
    baseServings: 4,
    prepTime: '15 min',
    cookTime: '5 min',
    ingredients: [
      { name: 'Full-fat milk', quantity: 4, unit: 'cups' },
      { name: 'Almonds', quantity: 15, unit: 'pcs' },
      { name: 'Cashews', quantity: 8, unit: 'pcs' },
      { name: 'Melon seeds', quantity: 1, unit: 'tbsp' },
      { name: 'Poppy seeds', quantity: 1, unit: 'tsp' },
      { name: 'Fennel seeds', quantity: 1, unit: 'tsp' },
      { name: 'Cardamom', quantity: 4, unit: 'pcs' },
      { name: 'Black pepper', quantity: 4, unit: 'pcs' },
      { name: 'Saffron strands', quantity: 5, unit: 'pcs' },
      { name: 'Sugar', quantity: 4, unit: 'tbsp' },
      { name: 'Rose water', quantity: 1, unit: 'tsp' },
    ],
    instructions: [
      'Soak almonds, cashews, melon seeds, poppy seeds, and fennel seeds for 2 hours.',
      'Grind soaked ingredients with cardamom, pepper, and a little milk into fine paste.',
      'Boil remaining milk with sugar and saffron.',
      'Add ground paste to milk and mix well.',
      'Add rose water. Strain if desired.',
      'Serve chilled.',
    ],
    pairings: [],
    notes: 'Traditional festival drink. Soaking nuts well is key to smooth texture.',
    difficulty: 'medium',
  },
  {
    id: 'nimbu-pani',
    name: 'Nimbu Pani (Lemonade)',
    category: 'drink',
    baseServings: 4,
    prepTime: '5 min',
    cookTime: '0 min',
    ingredients: [
      { name: 'Lemon juice', quantity: 4, unit: 'tbsp' },
      { name: 'Sugar', quantity: 3, unit: 'tbsp' },
      { name: 'Black salt', quantity: 0.5, unit: 'tsp' },
      { name: 'Cumin powder (roasted)', quantity: 0.25, unit: 'tsp' },
      { name: 'Water', quantity: 4, unit: 'cups' },
      { name: 'Ice cubes', quantity: 8, unit: 'pcs' },
      { name: 'Fresh mint', quantity: 4, unit: 'leaves' },
    ],
    instructions: [
      'Dissolve sugar in a little warm water.',
      'Add lemon juice, black salt, and cumin powder.',
      'Add cold water and ice cubes.',
      'Stir well and garnish with mint leaves.',
      'Serve immediately.',
    ],
    pairings: [],
    notes: 'Adjust sweet-sour balance to taste. Black salt adds a distinctive flavor.',
    difficulty: 'easy',
  },
  // ===== MORE SIDES =====
  {
    id: 'dahi-vada',
    name: 'Dahi Vada',
    category: 'side',
    baseServings: 4,
    prepTime: '20 min',
    cookTime: '20 min',
    ingredients: [
      { name: 'Urad dal', quantity: 1, unit: 'cup' },
      { name: 'Yogurt', quantity: 2, unit: 'cups' },
      { name: 'Cumin powder (roasted)', quantity: 0.5, unit: 'tsp' },
      { name: 'Red chili powder', quantity: 0.25, unit: 'tsp' },
      { name: 'Black salt', quantity: 0.25, unit: 'tsp' },
      { name: 'Sugar', quantity: 0.5, unit: 'tsp' },
      { name: 'Ginger', quantity: 0.5, unit: 'inch' },
      { name: 'Oil (for frying)', quantity: 'as needed', unit: '' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Soak urad dal for 4 hours. Grind into fluffy batter.',
      'Add salt and ginger. Mix well.',
      'Deep fry spoonfuls until golden. Soak in warm water 15 min.',
      'Squeeze water gently from vadas.',
      'Whisk yogurt with sugar and salt. Place vadas in yogurt.',
      'Top with cumin powder, red chili, and black salt. Chill and serve.',
    ],
    pairings: ['Peas Pulao', 'Vegetable Pulao'],
    notes: 'Soaking vadas in water makes them soft. Squeeze gently, do not press hard.',
    difficulty: 'medium',
  },
  {
    id: 'sabudana-khichdi',
    name: 'Sabudana Khichdi',
    category: 'side',
    baseServings: 4,
    prepTime: '8 hours',
    cookTime: '15 min',
    ingredients: [
      { name: 'Sabudana (tapioca pearls)', quantity: 1, unit: 'cup' },
      { name: 'Potato', quantity: 2, unit: 'medium' },
      { name: 'Peanuts (coarsely ground)', quantity: 0.25, unit: 'cup' },
      { name: 'Cumin seeds', quantity: 1, unit: 'tsp' },
      { name: 'Green chili', quantity: 2, unit: 'pcs' },
      { name: 'Curry leaves', quantity: 5, unit: 'pcs' },
      { name: 'Lemon juice', quantity: 1, unit: 'tbsp' },
      { name: 'Sugar', quantity: 0.5, unit: 'tsp' },
      { name: 'Oil/Ghee', quantity: 2, unit: 'tbsp' },
      { name: 'Fresh coriander', quantity: 2, unit: 'tbsp' },
      { name: 'Salt', quantity: 'to taste', unit: '' },
    ],
    instructions: [
      'Soak sabudana overnight (or at least 6 hours) with just enough water to cover.',
      'Heat oil, add cumin seeds and curry leaves.',
      'Add diced potato and cook until golden (5–7 min).',
      'Add green chili and ground peanuts.',
      'Add soaked sabudana, salt, and sugar. Cook 5 minutes on low heat.',
      'Add lemon juice and coriander. Serve warm.',
    ],
    pairings: ['Buttermilk', 'Raita'],
    notes: 'Perfect for fasting days (Ekadashi). Sabudana must be soaked well or it stays hard.',
    difficulty: 'easy',
  },
];
